### ISSUE TITLE
Testing: configurable cookie prefix

### ISSUE THREAD

**Issue by jimsafley** [omeka/plugin-Scripto#28]
The [cookie_prefix](https://github.com/omeka/plugin-Scripto/tree/cookie_prefix) branch fixes a bug that prevents users from logging in to Scripto when using MediaWiki 1.27.0+. The fix should be backwards compatible, so if you have an existing Scripto installation that works, it should still work without any changes.

Confirm that you can log in to Scripto when using a MediaWiki version that is <1.27.0 _and_ when using a MediaWiki version that is >=1.27.0. For the latter you must add a MediaWiki cookie prefix in plugin configuration.

**Comment by mebrett** [comment]
After much trial and tribulation trying to find the right cookie prefix (solution: edit Setup.php add `echo $wgCookiePrefix;exit;`, open page in MediaWiki and copy, then remove the line because it borks the api for Scripto), I can now say that it works with versions greater than 1.27.0

For our specific testing environment, the prefix was dbname_tablename_ but that may vary for other environments.

**Comment by jimsafley** [comment]
Yes, thanks to @mebrett's patience, we've found that the cookie prefix is predictably in one of the following formats:

- `<dbname>` if a table prefix is not used, -or-
- `<dbname>_<tableprefix>_` if a table prefix is used

`<dbname>` is the MediaWiki database name and `<tableprefix>` is the MediaWiki table prefix, in case one is being used. (Note the trailing underscore in the second format.)

**Comment by vchen-frick** [comment]
I'm very new to Omeka and Scripto. We seem to have the same exact issues as described here.

Can someone explain which file needs to be changed and what needs to be changed?

Following @jimsafley advice about the formatting led me to these instructions on [Configuring Scripto](https://omeka.org/classic/docs/Plugins/Scripto/#configuring-scripto). That pointed me to LocalSettings.php. 

We use a table Prefix, so should I add:
`$wgCookiePrefix =<dbname>_<tableprefix>_ ;` into the /public_html/wiki/LocalSettings.php?

I feel strange about editing /public_html/wiki/includes/Setup.php because I feel like everything inside the includes folder shouldn't be touched.

Also, in Setup.php, I don't see "echo $wgCookiePrefix;exit;" I'm not sure which line to remove.

**Comment by jimsafley** [comment]
You add the MediaWiki cookie prefix directly in Omeka, in Scripto's configuration page. Go to "Plugins > Scripto [Configure]" and you should see the "MediaWiki cookie prefix" input.

**Comment by vchen-frick** [comment]
I don't see that at all when I go to the Configure Plugin: Scripto on the browser.

**Comment by jimsafley** [comment]
It's in the newest version of Scripto (2.3) https://omeka.org/classic/plugins/Scripto/

**Comment by vchen-frick** [comment]
I see. We have 2.2. So once we update to 2.3, we should see a setting for "MediaWiki cookie prefix" textbox. Then is that were you enter <dbname>_<tableprefix>_?

**Comment by jimsafley** [comment]
yes

**Comment by vchen-frick** [comment]
Thanks @jimsafley! Just updated to the latest version 2.3.2 and that fixed this issue for us.
