### ISSUE TITLE
InvalidArgumentException Could not find file css/scripto-transcribe.css!

### ISSUE THREAD

**Issue by ValeryCC** [omeka/plugin-Scripto#31]
Got this error message with 2.4 upgrade.

I searched for any CSS file in the scripto directory and found one here:
/public_html/plugins/Scripto/views/shared/javascripts/theme/default/style.css

However, it was looking for css/scripto-transcribe.css. So I moved the theme directory up to shared and rename it css, and renamed the file scripto-transcribe.css, so that it lives here:
/public_html/plugins/Scripto/views/shared/css/scripto-transcribe.css

And that fixed the issue.

InvalidArgumentException: Could not find file css/scripto-transcribe.css! in /home/xxx/public_html/application/libraries/globals.php:1288
Stack trace:
#0 /home/xxx/public_html/application/libraries/globals.php(1247): web_path_to('css/scripto-tra...')
#1 /home/xxx/public_html/application/libraries/globals.php(1193): src('css/scripto-tra...', 'css', 'css', '2.7.1')
#2 /home/xxx/public_html/application/libraries/globals.php(1093): css_src('scripto-transcr...', 'css', '2.7.1')
#3 /home/xxx/public_html/themes/Scribe/scripto/index/transcribe.php(3): queue_css_file('scripto-transcr...')
#4 /home/xxx/public_html/application/libraries/Omeka/View.php(114): include('/home/xxx/...')
#5 /home/xxx/public_html/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run('/home/xxx/...')
#6 /home/xxx/public_html/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render(NULL)
#7 /home/xxx/public_html/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('index/transcrib...', NULL)
#8 /home/xxx/public_html/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render()
#9 /home/xxx/public_html/application/libraries/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#10 /home/xxx/public_html/application/libraries/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#11 /home/xxx/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('transcribeActio...')
#12 /home/xxx/public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#13 /home/xxx/public_html/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#14 /home/xxx/public_html/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#15 /home/xxx/public_html/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#16 /home/xxx/public_html/index.php(23): Omeka_Application->run()
#17 {main}

**Comment by zerocrates** [comment]
This is the same basic problem as your other issue.

The Scribe theme is apparently very tightly coupled to the "ui-libraries" fork of Scripto, so you can't just switch over to this version and have the theme still work. We don't have any control over this theme, or the fork of Scripto. 

Putting any file in the right path, as you did here, will stop this error from happening, but the file you moved doesn't have the same contents as the one from the fork, so there are likely to be other problems (especially if you simply moved the file and didn't copy it, since it's needed in its original location).

You basically have the following options:

- Stop using the Scribe theme
- Keep using the Scribe theme, and stay on the older version of Scripto that the ui-libraries fork uses
- Convince ui-libraries to update their fork to include the updates to Scripto (resulting in a newer version of the fork)
- Convince ui-libraries to submit their relevant changes to Scripto as pull requests, so the fork is no longer necessary
- Rewrite (or convince someone to rewrite) the Scribe theme so it does not depend on the fork

There appears to be some continuing development on the Scripto fork being used here, so there should be some workable solution here, but it's not something that issues just filed to this repository is going to resolve.

**Comment by ValeryCC** [comment]
Again thank you very much for explaining our available options! That is extremely helpful. Apologies for opening a bug report in the wrong plugin!
